"""
AICines Content Intelligence Engine
------------------------------------

Reusable recommendation engine derived from the validated methodology
developed in Notebook 07 and the engagement model trained in Notebook 06.

Responsibilities:
- Load processed project data
- Load the saved engagement model
- Load the frozen 53-feature contract
- Build TF-IDF content representations
- Generate candidate content
- Filter previously seen content
- Construct point-in-time recommendation features
- Score candidates with the real Random Forest model
- Apply freshness + diversity + exploration ranking
- Handle new-user cold start
- Handle new-content cold start
- Generate human-readable recommendation explanations
- Expose recommendation progress through a callback

IMPORTANT:
This module contains no Streamlit/UI code.
The dashboard should call this module rather than duplicate
recommendation logic.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Optional
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import joblib
import numpy as np
import pandas as pd



# ---------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------

ProgressCallback = Optional[Callable[[str], None]]


@dataclass
class RecommendationResult:
    """
    Structured output from the recommendation engine.
    """

    user_id: str
    recommendations: list[str]
    details: pd.DataFrame
    stages: list[str]


# ---------------------------------------------------------------------
# Main recommendation engine
# ---------------------------------------------------------------------

class RecommendationEngine:
    """
    Production-style reusable recommendation engine.

    The engine uses:
        1. TF-IDF candidate generation
        2. Historical user/content/creator features
        3. The saved Random Forest engagement model
        4. Freshness
        5. Diversity
        6. Exploration
    """

    def __init__(
        self,
        project_root: str | Path | None = None,
        model_path: str | Path | None = None,
        feature_columns_path: str | Path | None = None,
        candidate_pool_size: int = 200,
        random_state: int = 42,
    ) -> None:

        # -------------------------------------------------------------
        # Project paths
        # -------------------------------------------------------------

        if project_root is None:
            # recommend.py is:
            # project_root/src/recommender/recommend.py
            self.project_root = Path(__file__).resolve().parents[2]
        else:
            self.project_root = Path(project_root).resolve()

        self.data_dir = self.project_root / "data" / "processed"
        self.models_dir = self.project_root / "models"

        self.model_path = (
            Path(model_path)
            if model_path is not None
            else self.models_dir / "random_forest_engagement.joblib"
        )

        self.feature_columns_path = (
            Path(feature_columns_path)
            if feature_columns_path is not None
            else self.models_dir / "engagement_feature_columns.joblib"
        )

        self.candidate_pool_size = candidate_pool_size
        self.random_state = random_state

        # -------------------------------------------------------------
        # Load core assets
        # -------------------------------------------------------------

        self._load_data()
        self._load_model()

        # -------------------------------------------------------------
        # Build recommendation structures
        # -------------------------------------------------------------

        self._prepare_serving_cutoff()
        self._build_seen_mapping()
        self._build_statistics()
        self._build_tfidf()

        self._validate_model_contract()

    # =================================================================
    # Progress helper
    # =================================================================

    @staticmethod
    def _progress(
        callback: ProgressCallback,
        message: str,
        stages: list[str],
    ) -> None:
        """
        Record and optionally display a completed processing stage.
        """

        stages.append(message)

        if callback is not None:
            callback(message)

    # =================================================================
    # Data loading
    # =================================================================

    def _load_data(self) -> None:
        """
        Load the processed datasets generated by the earlier notebooks.
        """

        users_path = self.data_dir / "users_clean.csv"
        creators_path = self.data_dir / "creators_clean.csv"
        content_path = self.data_dir / "content_clean.csv"
        interactions_path = self.data_dir / "interactions_clean.csv"

        required_files = [
            users_path,
            creators_path,
            content_path,
            interactions_path,
        ]

        missing = [str(path) for path in required_files if not path.exists()]

        if missing:
            raise FileNotFoundError(
                "Required processed data files are missing:\n"
                + "\n".join(missing)
            )

        self.users = pd.read_csv(users_path)
        self.creators = pd.read_csv(creators_path)
        self.content = pd.read_csv(content_path)
        self.interactions = pd.read_csv(interactions_path)

        # -------------------------------------------------------------
        # Date parsing
        # -------------------------------------------------------------

        self.users["signup_date"] = pd.to_datetime(
            self.users["signup_date"],
            errors="coerce",
        )

        self.creators["signup_date"] = pd.to_datetime(
            self.creators["signup_date"],
            errors="coerce",
        )

        self.content["created_at"] = pd.to_datetime(
            self.content["created_at"],
            errors="coerce",
        )

        self.interactions["timestamp"] = pd.to_datetime(
            self.interactions["timestamp"],
            errors="coerce",
        )

        self.interactions["content_created_at"] = pd.to_datetime(
            self.interactions["content_created_at"],
            errors="coerce",
        )

        # -------------------------------------------------------------
        # Basic validation
        # -------------------------------------------------------------

        required_interaction_columns = {
            "user_id",
            "content_id",
            "creator_id",
            "genre",
            "content_type",
            "duration",
            "timestamp",
            "clicked",
            "watch_time",
            "completion_rate",
            "meaningful_engagement",
        }

        missing_interaction_columns = (
            required_interaction_columns
            - set(self.interactions.columns)
        )

        if missing_interaction_columns:
            raise ValueError(
                "Interactions dataset is missing required columns: "
                f"{sorted(missing_interaction_columns)}"
            )

        if self.interactions.empty:
            raise ValueError("Interactions dataset is empty.")

        if self.content.empty:
            raise ValueError("Content dataset is empty.")

        if self.users.empty:
            raise ValueError("Users dataset is empty.")

        if self.creators.empty:
            raise ValueError("Creators dataset is empty.")

    # =================================================================
    # Model loading
    # =================================================================

    def _load_model(self) -> None:
        """
        Load the actual trained Random Forest pipeline and frozen
        feature-column contract.
        """

        if not self.model_path.exists():
            raise FileNotFoundError(
                f"Engagement model not found: {self.model_path}"
            )

        if not self.feature_columns_path.exists():
            raise FileNotFoundError(
                "Feature contract not found: "
                f"{self.feature_columns_path}"
            )

        self.model = joblib.load(self.model_path)
        self.feature_columns = joblib.load(
            self.feature_columns_path
        )

        if not isinstance(self.feature_columns, list):
            self.feature_columns = list(self.feature_columns)

    # =================================================================
    # Serving cutoff
    # =================================================================

    def _prepare_serving_cutoff(self) -> None:
        """
        Use the latest observed interaction timestamp as the serving
        cutoff.

        This means all historical statistics used by the dashboard
        are constructed from observations available before the
        recommendation request.
        """

        self.serving_cutoff = self.interactions["timestamp"].max()

        if pd.isna(self.serving_cutoff):
            raise ValueError("Unable to determine serving cutoff.")

        self.historical_interactions = self.interactions[
            self.interactions["timestamp"] <= self.serving_cutoff
        ].copy()

        # Content available by serving time.
        self.eligible_content = self.content[
            self.content["created_at"] <= self.serving_cutoff
        ].copy()

        if self.eligible_content.empty:
            raise ValueError(
                "No eligible content exists at the serving cutoff."
            )

    # =================================================================
    # Seen-content mapping
    # =================================================================

    def _build_seen_mapping(self) -> None:
        """
        Build the set of content previously interacted with by each user.
        """

        self.seen_content = (
            self.historical_interactions
            .groupby("user_id")["content_id"]
            .apply(set)
            .to_dict()
        )

    # =================================================================
    # Historical statistics
    # =================================================================

    def _build_statistics(self) -> None:
        """
        Construct the historical statistics used by Notebook 07's
        recommendation feature pipeline.

        These are aggregate historical observations and do not use
        the current recommendation outcome.
        """

        hist = self.historical_interactions.copy()

        # -------------------------------------------------------------
        # Global statistics
        # -------------------------------------------------------------

        self.global_interactions = len(hist)

        self.global_engagements = int(
            hist["meaningful_engagement"].sum()
        )

        if self.global_interactions > 0:
            self.global_engagement_rate = (
                self.global_engagements
                / self.global_interactions
            )
        else:
            self.global_engagement_rate = 0.5

        # -------------------------------------------------------------
        # User statistics
        # -------------------------------------------------------------

        user_group = hist.groupby("user_id")

        self.user_stats = user_group.agg(
            user_prior_interactions=("content_id", "count"),
            user_prior_clicks=("clicked", "sum"),
            user_prior_engagements=(
                "meaningful_engagement",
                "sum",
            ),
            user_prior_watch_time=("watch_time", "sum"),
            user_prior_completions=(
                "completion_rate",
                "sum",
            ),
            user_prior_active_days=(
                "timestamp",
                lambda x: x.dt.date.nunique(),
            ),
            user_prior_unique_content=(
                "content_id",
                "nunique",
            ),
            user_prior_unique_creators=(
                "creator_id",
                "nunique",
            ),
        )

        self.user_stats["user_prior_ctr"] = (
            self.user_stats["user_prior_clicks"]
            / self.user_stats["user_prior_interactions"]
        )

        self.user_stats["user_prior_engagement_rate"] = (
            self.user_stats["user_prior_engagements"]
            / self.user_stats["user_prior_interactions"]
        )

        self.user_stats["user_prior_avg_watch_time"] = (
            self.user_stats["user_prior_watch_time"]
            / self.user_stats["user_prior_interactions"]
        )

        self.user_stats["user_prior_avg_completion"] = (
            self.user_stats["user_prior_completions"]
            / self.user_stats["user_prior_interactions"]
        )

        # -------------------------------------------------------------
        # Creator statistics
        # -------------------------------------------------------------

        creator_group = hist.groupby("creator_id")

        self.creator_stats = creator_group.agg(
            creator_prior_interactions=("content_id", "count"),
            creator_prior_clicks=("clicked", "sum"),
            creator_prior_engagements=(
                "meaningful_engagement",
                "sum",
            ),
        )

        self.creator_stats["creator_prior_ctr"] = (
            self.creator_stats["creator_prior_clicks"]
            / self.creator_stats["creator_prior_interactions"]
        )

        self.creator_stats["creator_prior_engagement_rate"] = (
            self.creator_stats["creator_prior_engagements"]
            / self.creator_stats["creator_prior_interactions"]
        )

        # -------------------------------------------------------------
        # Content statistics
        # -------------------------------------------------------------

        content_group = hist.groupby("content_id")

        self.content_stats = content_group.agg(
            content_prior_interactions=("user_id", "count"),
            content_prior_clicks=("clicked", "sum"),
            content_prior_engagements=(
                "meaningful_engagement",
                "sum",
            ),
        )

        self.content_stats["content_prior_ctr"] = (
            self.content_stats["content_prior_clicks"]
            / self.content_stats["content_prior_interactions"]
        )

        self.content_stats["content_prior_engagement_rate"] = (
            self.content_stats["content_prior_engagements"]
            / self.content_stats["content_prior_interactions"]
        )

        # -------------------------------------------------------------
        # User-content statistics
        # -------------------------------------------------------------

        user_content_group = hist.groupby(
            ["user_id", "content_id"]
        )

        self.user_content_stats = user_content_group.agg(
            user_content_prior_interactions=("user_id", "count"),
            user_content_prior_clicks=("clicked", "sum"),
            user_content_prior_engagements=(
                "meaningful_engagement",
                "sum",
            ),
        )

        self.user_content_stats[
            "user_content_prior_ctr"
        ] = (
            self.user_content_stats[
                "user_content_prior_clicks"
            ]
            / self.user_content_stats[
                "user_content_prior_interactions"
            ]
        )

        self.user_content_stats[
            "user_content_prior_engagement_rate"
        ] = (
            self.user_content_stats[
                "user_content_prior_engagements"
            ]
            / self.user_content_stats[
                "user_content_prior_interactions"
            ]
        )

        # -------------------------------------------------------------
        # User-genre statistics
        # -------------------------------------------------------------

        user_genre_group = hist.groupby(
            ["user_id", "genre"]
        )

        self.user_genre_stats = user_genre_group.agg(
            user_genre_prior_interactions=("user_id", "count"),
            user_genre_prior_clicks=("clicked", "sum"),
            user_genre_prior_engagements=(
                "meaningful_engagement",
                "sum",
            ),
        )

        self.user_genre_stats[
            "user_genre_prior_engagement_rate"
        ] = (
            self.user_genre_stats[
                "user_genre_prior_engagements"
            ]
            / self.user_genre_stats[
                "user_genre_prior_interactions"
            ]
        )

        # -------------------------------------------------------------
        # Recent popularity
        # -------------------------------------------------------------

        recent_cutoff = (
            self.serving_cutoff
            - pd.Timedelta(days=30)
        )

        recent_hist = hist[
            hist["timestamp"] >= recent_cutoff
        ]

        self.recent_popularity = (
            recent_hist.groupby("content_id")
            .agg(
                recent_interactions=("content_id", "count"),
                recent_engagements=(
                    "meaningful_engagement",
                    "sum",
                ),
            )
        )

        # -------------------------------------------------------------
        # Fill numerical statistics
        # -------------------------------------------------------------

        statistic_frames = [
            self.user_stats,
            self.creator_stats,
            self.content_stats,
            self.user_content_stats,
            self.user_genre_stats,
        ]

        for frame in statistic_frames:
            numeric_columns = frame.select_dtypes(
                include=np.number
            ).columns

            frame[numeric_columns] = (
                frame[numeric_columns]
                .replace([np.inf, -np.inf], np.nan)
                .fillna(0)
            )

        self.recent_popularity = (
            self.recent_popularity
            .replace([np.inf, -np.inf], np.nan)
            .fillna(0)
        )

    # =================================================================
    # Smoothed historical rates
    # =================================================================

    def _smoothed_rate(
        self,
        successes: pd.Series,
        interactions: pd.Series,
        alpha: float = 10.0,
    ) -> pd.Series:
        """
        Apply the same empirical-Bayes-style smoothing principle used
        in Notebook 05.

        The prior is the platform-level historical engagement rate.
        """

        return (
            successes
            + alpha * self.global_engagement_rate
        ) / (
            interactions + alpha
        )

    # =================================================================
    # TF-IDF representation
    # =================================================================

    def _build_tfidf(self) -> None:
        """
        Build the content-based representation used by Notebook 07.

        Representation:
            genre
            content type
            duration bucket
            creator identity
        """

        content_features = self.eligible_content[
            [
                "content_id",
                "creator_id",
                "genre",
                "content_type",
                "duration",
            ]
        ].copy()

        content_features = content_features.reset_index(
            drop=True
        )

        content_features["duration_bucket"] = pd.cut(
            content_features["duration"],
            bins=[
                0,
                10,
                20,
                30,
                60,
                120,
                300,
                np.inf,
            ],
            labels=[
                "very_short",
                "short",
                "medium",
                "long",
                "very_long",
                "extended",
                "very_extended",
            ],
            include_lowest=True,
        )

        content_features["genre_token"] = (
            content_features["genre"]
            .astype(str)
            .str.lower()
            .str.replace("-", "_", regex=False)
        )

        content_features["type_token"] = (
            content_features["content_type"]
            .astype(str)
            .str.lower()
        )

        content_features["duration_token"] = (
            content_features["duration_bucket"]
            .astype(str)
            .str.lower()
        )

        content_features["creator_token"] = (
            content_features["creator_id"]
            .astype(str)
            .str.lower()
        )

        content_features["content_text"] = (
            "genre_"
            + content_features["genre_token"]
            + " type_"
            + content_features["type_token"]
            + " duration_"
            + content_features["duration_token"]
            + " creator_"
            + content_features["creator_token"]
        )

        self.content_features = content_features

        self.vectorizer = TfidfVectorizer(
            lowercase=True,
            token_pattern=r"(?u)\b\w+\b",
        )

        self.content_matrix = self.vectorizer.fit_transform(
            content_features["content_text"]
        )

        self.content_id_to_index = pd.Series(
            content_features.index,
            index=content_features["content_id"],
        )

    # =================================================================
    # Model contract
    # =================================================================

    def _validate_model_contract(self) -> None:
        """
        Confirm that the recommendation engine still produces exactly
        the feature contract used by the trained model.

        The model was trained using 53 frozen features.
        """

        expected_feature_count = len(
            self.feature_columns
        )

        if expected_feature_count != 53:
            raise ValueError(
                "Expected 53 model features, but loaded "
                f"{expected_feature_count}."
            )

    # =================================================================
    # User lookup
    # =================================================================

    def _get_user(self, user_id: str) -> pd.Series:
        """
        Return the requested user's static profile.
        """

        matches = self.users[
            self.users["user_id"].astype(str)
            == str(user_id)
        ]

        if matches.empty:
            raise ValueError(
                f"User '{user_id}' does not exist."
            )

        return matches.iloc[0]

    # =================================================================
    # Candidate generation
    # =================================================================

    def _build_user_profile(
        self,
        user_id: str,
    ):
        """
        Build a TF-IDF user profile from the user's historically
        interacted-with content.

        Meaningful-engagement interactions receive higher importance.

        The returned profile is explicitly converted to a standard
        NumPy array so it is compatible with sklearn's cosine_similarity.
        """

        user_history = self.historical_interactions[
            self.historical_interactions["user_id"].astype(str)
            == str(user_id)
        ].copy()

        if user_history.empty:
            return None

        # -------------------------------------------------------------
        # Keep only historical content that exists in the TF-IDF
        # representation.
        # -------------------------------------------------------------

        valid_history = user_history[
            user_history["content_id"].isin(
                self.content_id_to_index.index
            )
        ].copy()

        if valid_history.empty:
            return None

        # -------------------------------------------------------------
        # Use unique content items so repeated interactions with the
        # same content do not duplicate the same TF-IDF representation.
        # -------------------------------------------------------------

        valid_history = (
            valid_history
            .drop_duplicates(
                subset=["content_id"],
                keep="last",
            )
            .reset_index(drop=True)
        )

        history_indices = [
            self.content_id_to_index[content_id]
            for content_id in valid_history["content_id"]
        ]

        if not history_indices:
            return None

        history_matrix = self.content_matrix[
            history_indices
        ]

        # -------------------------------------------------------------
        # Weight content by meaningful engagement.
        #
        # +0.25 ensures that even non-engaged historical interactions
        # contribute a small amount to the user's profile.
        # -------------------------------------------------------------

        weights = (
            valid_history["meaningful_engagement"]
            .astype(float)
            .to_numpy()
            + 0.25
        )

        weighted_matrix = history_matrix.multiply(
            weights[:, None]
        )

        # -------------------------------------------------------------
        # Average the weighted content representations.
        #
        # scipy sparse mean(axis=0) returns np.matrix.
        # Convert explicitly to a normal NumPy ndarray.
        # -------------------------------------------------------------

        user_profile = weighted_matrix.mean(
            axis=0
        )

        user_profile = np.asarray(
            user_profile
        )

        # cosine_similarity expects a 2D matrix.
        if user_profile.ndim == 1:
            user_profile = user_profile.reshape(
                1,
                -1,
            )

        return user_profile

    def _generate_content_candidates(
        self,
        user_id: str,
        candidate_pool_size: Optional[int] = None,
    ) -> pd.DataFrame:
        """
        Generate candidates using the Notebook 07 TF-IDF content
        similarity approach.
        """

        if candidate_pool_size is None:
            candidate_pool_size = self.candidate_pool_size

        user_profile = self._build_user_profile(
            user_id
        )

        # -------------------------------------------------------------
        # Cold-start user
        # -------------------------------------------------------------

        if user_profile is None:
            return self._cold_start_candidates(
                user_id=user_id,
                candidate_pool_size=candidate_pool_size,
            )

        similarity_scores = cosine_similarity(
            user_profile,
            self.content_matrix,
        ).ravel()

        candidate_frame = self.content_features[
            [
                "content_id",
                "creator_id",
                "genre",
                "content_type",
                "duration",
                "duration_bucket",
            ]
        ].copy()

        candidate_frame["similarity_score"] = (
            similarity_scores
        )

        # -------------------------------------------------------------
        # Remove previously seen content
        # -------------------------------------------------------------

        seen = self.seen_content.get(
            user_id,
            set(),
        )

        candidate_frame = candidate_frame[
            ~candidate_frame["content_id"].isin(seen)
        ].copy()

        # -------------------------------------------------------------
        # Select top TF-IDF candidates
        # -------------------------------------------------------------

        candidate_frame = (
            candidate_frame
            .sort_values(
                "similarity_score",
                ascending=False,
            )
            .head(candidate_pool_size)
            .reset_index(drop=True)
        )

        return candidate_frame

    # =================================================================
    # Cold-start candidate generation
    # =================================================================

    def _cold_start_candidates(
        self,
        user_id: str,
        candidate_pool_size: int,
    ) -> pd.DataFrame:
        """
        New-user fallback.

        Since a user has no history, use recent/popular content
        rather than pretending we know their preferences.
        """

        candidates = self.eligible_content[
            [
                "content_id",
                "creator_id",
                "genre",
                "content_type",
                "duration",
            ]
        ].copy()

        recent_stats = (
            self.recent_popularity
            .reset_index()
        )

        candidates = candidates.merge(
            recent_stats[
                [
                    "content_id",
                    "recent_interactions",
                    "recent_engagements",
                ]
            ],
            on="content_id",
            how="left",
        )

        candidates[
            "recent_interactions"
        ] = candidates[
            "recent_interactions"
        ].fillna(0)

        candidates[
            "recent_engagements"
        ] = candidates[
            "recent_engagements"
        ].fillna(0)

        candidates["similarity_score"] = 0.0

        candidates["popularity_score"] = (
            candidates["recent_interactions"]
            + 2.0
            * candidates["recent_engagements"]
        )

        seen = self.seen_content.get(
            user_id,
            set(),
        )

        candidates = candidates[
            ~candidates["content_id"].isin(seen)
        ].copy()

        candidates = (
            candidates
            .sort_values(
                [
                    "popularity_score",
                    "recent_interactions",
                ],
                ascending=False,
            )
            .head(candidate_pool_size)
            .reset_index(drop=True)
        )

        return candidates

    # =================================================================
    # Recommendation feature construction
    # =================================================================

    def _build_candidate_features(
        self,
        user_id: str,
        candidates: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Construct the frozen 53-feature model input.

        This mirrors the feature families from Notebook 05/07.
        """

        user = self._get_user(user_id)

        df = candidates.copy()

        # -------------------------------------------------------------
        # Creator-level static features
        # -------------------------------------------------------------
        # Notebook 07 obtains creator follower count from the creators
        # table. The original column is "followers".
        #
        # The trained model expects "creator_followers".
        # -------------------------------------------------------------

        creator_static = self.creators[
            [
                "creator_id",
                "followers",
                "creator_type",
            ]
        ].copy()

        creator_static = creator_static.rename(
            columns={
                "followers": "creator_followers",
            }
        )

        df = df.merge(
            creator_static,
            on="creator_id",
            how="left",
        )

        # -------------------------------------------------------------
        # Static user features
        # -------------------------------------------------------------

        df["age_group"] = user["age_group"]
        df["country"] = user["country"]
        df["following_count"] = user["following_count"]
        df["creator_flag"] = user["creator_flag"]

        # -------------------------------------------------------------
        # Static user features
        # -------------------------------------------------------------

        df["age_group"] = user["age_group"]
        df["country"] = user["country"]
        df["following_count"] = user["following_count"]
        df["creator_flag"] = user["creator_flag"]

        # -------------------------------------------------------------
        # Creator static information
        # -------------------------------------------------------------

        creator_static = self.creators[
            [
                "creator_id",
                "creator_type",
            ]
        ].copy()

        df = df.merge(
            creator_static,
            on="creator_id",
            how="left",
            suffixes=("", "_creator"),
        )

        # -------------------------------------------------------------
        # Content temporal features
        # -------------------------------------------------------------

        content_created = (
            self.eligible_content[
                [
                    "content_id",
                    "created_at",
                ]
            ]
            .drop_duplicates("content_id")
        )

        df = df.merge(
            content_created,
            on="content_id",
            how="left",
        )

        df["content_age_days"] = (
            self.serving_cutoff
            - df["created_at"]
        ).dt.total_seconds() / (
            24 * 60 * 60
        )

        df["content_age_days"] = (
            df["content_age_days"]
            .clip(lower=0)
        )

        df["freshness"] = np.exp(
            -df["content_age_days"] / 30.0
        )

        # -------------------------------------------------------------
        # Serving context
        # -------------------------------------------------------------

        interaction_hour = (
            self.serving_cutoff.hour
        )

        interaction_day = (
            self.serving_cutoff.dayofweek
        )

        df["interaction_hour"] = (
            interaction_hour
        )

        df["interaction_day_of_week"] = (
            interaction_day
        )

        df["is_weekend"] = int(
            interaction_day >= 5
        )

        df["hour_sin"] = np.sin(
            2
            * np.pi
            * interaction_hour
            / 24
        )

        df["hour_cos"] = np.cos(
            2
            * np.pi
            * interaction_hour
            / 24
        )

        # -------------------------------------------------------------
        # User tenure
        # -------------------------------------------------------------

        df["user_tenure_days"] = (
            self.serving_cutoff
            - pd.Timestamp(
                user["signup_date"]
            )
        ).total_seconds() / (
            24 * 60 * 60
        )

        # -------------------------------------------------------------
        # User history
        # -------------------------------------------------------------

        user_history = self.user_stats.loc[
            user_id
        ] if user_id in self.user_stats.index else None

        if user_history is None:

            user_values = {
                "user_prior_interactions": 0,
                "user_prior_clicks": 0,
                "user_prior_engagements": 0,
                "user_prior_watch_time": 0,
                "user_prior_completions": 0,
                "user_prior_ctr": 0,
                "user_prior_engagement_rate": 0,
                "user_prior_avg_watch_time": 0,
                "user_prior_avg_completion": 0,
                "user_prior_active_days": 0,
                "user_prior_unique_content": 0,
                "user_prior_unique_creators": 0,
            }

        else:

            user_values = {
                column: user_history[column]
                for column in [
                    "user_prior_interactions",
                    "user_prior_clicks",
                    "user_prior_engagements",
                    "user_prior_watch_time",
                    "user_prior_completions",
                    "user_prior_ctr",
                    "user_prior_engagement_rate",
                    "user_prior_avg_watch_time",
                    "user_prior_avg_completion",
                    "user_prior_active_days",
                    "user_prior_unique_content",
                    "user_prior_unique_creators",
                ]
            }

        for column, value in user_values.items():
            df[column] = value

        # -------------------------------------------------------------
        # Creator history
        # -------------------------------------------------------------

        creator_history = (
            self.creator_stats
            .reindex(df["creator_id"])
            .reset_index(drop=True)
        )

        for column in [
            "creator_prior_interactions",
            "creator_prior_clicks",
            "creator_prior_engagements",
            "creator_prior_ctr",
            "creator_prior_engagement_rate",
        ]:
            df[column] = (
                creator_history[column]
                .fillna(0)
                .to_numpy()
            )

        # -------------------------------------------------------------
        # Content history
        # -------------------------------------------------------------

        content_history = (
            self.content_stats
            .reindex(df["content_id"])
            .reset_index(drop=True)
        )

        for column in [
            "content_prior_interactions",
            "content_prior_clicks",
            "content_prior_engagements",
            "content_prior_ctr",
            "content_prior_engagement_rate",
        ]:
            df[column] = (
                content_history[column]
                .fillna(0)
                .to_numpy()
            )

        # -------------------------------------------------------------
        # User-content history
        # -------------------------------------------------------------

        user_content_keys = pd.MultiIndex.from_arrays(
            [
                [user_id] * len(df),
                df["content_id"].to_numpy(),
            ],
            names=[
                "user_id",
                "content_id",
            ],
        )

        user_content_history = (
            self.user_content_stats
            .reindex(user_content_keys)
            .reset_index(drop=True)
        )

        for column in [
            "user_content_prior_interactions",
            "user_content_prior_clicks",
            "user_content_prior_engagements",
            "user_content_prior_ctr",
            "user_content_prior_engagement_rate",
        ]:
            df[column] = (
                user_content_history[column]
                .fillna(0)
                .to_numpy()
            )

        # -------------------------------------------------------------
        # User-genre history
        # -------------------------------------------------------------

        user_genre_keys = pd.MultiIndex.from_arrays(
            [
                [user_id] * len(df),
                df["genre"].to_numpy(),
            ],
            names=[
                "user_id",
                "genre",
            ],
        )

        user_genre_history = (
            self.user_genre_stats
            .reindex(user_genre_keys)
            .reset_index(drop=True)
        )

        for column in [
            "user_genre_prior_interactions",
            "user_genre_prior_clicks",
            "user_genre_prior_engagements",
            "user_genre_prior_engagement_rate",
        ]:
            df[column] = (
                user_genre_history[column]
                .fillna(0)
                .to_numpy()
            )

        # -------------------------------------------------------------
        # Smoothed rates
        # -------------------------------------------------------------

        df["user_prior_smoothed_engagement_rate"] = (
            self._smoothed_rate(
                pd.Series(
                    df["user_prior_engagements"],
                    index=df.index,
                ),
                pd.Series(
                    df["user_prior_interactions"],
                    index=df.index,
                ),
            )
        )

        df["creator_prior_smoothed_engagement_rate"] = (
            self._smoothed_rate(
                pd.Series(
                    df["creator_prior_engagements"],
                    index=df.index,
                ),
                pd.Series(
                    df["creator_prior_interactions"],
                    index=df.index,
                ),
            )
        )

        df["content_prior_smoothed_engagement_rate"] = (
            self._smoothed_rate(
                pd.Series(
                    df["content_prior_engagements"],
                    index=df.index,
                ),
                pd.Series(
                    df["content_prior_interactions"],
                    index=df.index,
                ),
            )
        )

        df[
            "user_content_prior_smoothed_engagement_rate"
        ] = self._smoothed_rate(
            pd.Series(
                df[
                    "user_content_prior_engagements"
                ],
                index=df.index,
            ),
            pd.Series(
                df[
                    "user_content_prior_interactions"
                ],
                index=df.index,
            ),
        )

        df[
            "user_genre_prior_smoothed_engagement_rate"
        ] = self._smoothed_rate(
            pd.Series(
                df[
                    "user_genre_prior_engagements"
                ],
                index=df.index,
            ),
            pd.Series(
                df[
                    "user_genre_prior_interactions"
                ],
                index=df.index,
            ),
        )

        # -------------------------------------------------------------
        # Clean numerical values
        # -------------------------------------------------------------

        numerical_columns = df.select_dtypes(
            include=np.number
        ).columns

        df[numerical_columns] = (
            df[numerical_columns]
            .replace(
                [np.inf, -np.inf],
                np.nan,
            )
            .fillna(0)
        )

        # -------------------------------------------------------------
        # Validate model contract
        # -------------------------------------------------------------

        missing_features = [
            feature
            for feature in self.feature_columns
            if feature not in df.columns
        ]

        if missing_features:
            raise ValueError(
                "Missing model features: "
                f"{missing_features}"
            )

        model_features = df[
            self.feature_columns
        ].copy()

        if list(model_features.columns) != list(
            self.feature_columns
        ):
            raise ValueError(
                "Model feature order does not match "
                "the frozen feature contract."
            )

        if model_features.shape[1] != 53:
            raise ValueError(
                "Model feature matrix contains "
                f"{model_features.shape[1]} columns; "
                "expected 53."
            )

        if model_features.isna().any().any():
            raise ValueError(
                "Missing values detected in model features."
            )

        return df

    # =================================================================
    # Model scoring
    # =================================================================

    def _score_candidates(
        self,
        candidate_features: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Score candidates using the actual saved Random Forest model.
        """

        model_input = candidate_features[
            self.feature_columns
        ]

        probabilities = self.model.predict_proba(
            model_input
        )[:, 1]

        scored = candidate_features.copy()

        scored["engagement_score"] = (
            probabilities
        )

        return scored

    # =================================================================
    # Diversity-aware final ranking
    # =================================================================

    def _build_final_feed(
        self,
        scored_candidates: pd.DataFrame,
        k: int = 10,
    ) -> pd.DataFrame:
        """
        Apply the final feed-ranking policy used in Notebook 07.

        Components:
            engagement = 0.75
            freshness  = 0.15
            exploration = 0.10

        Diversity penalties:
            repeated creator = 0.10
            repeated genre   = 0.05

        These weights are policy choices validated through the offline
        evaluation workflow; they should not be presented as learned
        parameters.
        """

        df = scored_candidates.copy()

        if df.empty:
            return df

        # -------------------------------------------------------------
        # Normalize engagement
        # -------------------------------------------------------------

        score_min = df["engagement_score"].min()
        score_max = df["engagement_score"].max()

        if score_max > score_min:
            df["normalized_engagement"] = (
                (
                    df["engagement_score"]
                    - score_min
                )
                / (
                    score_max
                    - score_min
                )
            )
        else:
            df["normalized_engagement"] = 0.5

        # -------------------------------------------------------------
        # Normalize freshness
        # -------------------------------------------------------------

        freshness_min = df["freshness"].min()
        freshness_max = df["freshness"].max()

        if freshness_max > freshness_min:
            df["normalized_freshness"] = (
                (
                    df["freshness"]
                    - freshness_min
                )
                / (
                    freshness_max
                    - freshness_min
                )
            )
        else:
            df["normalized_freshness"] = 0.5

        # -------------------------------------------------------------
        # Reproducible exploration
        # -------------------------------------------------------------

        rng = np.random.default_rng(
            self.random_state
        )

        df["exploration_score"] = rng.random(
            len(df)
        )

        # -------------------------------------------------------------
        # Base feed score
        # -------------------------------------------------------------

        df["base_feed_score"] = (
            0.75
            * df["normalized_engagement"]
            + 0.15
            * df["normalized_freshness"]
            + 0.10
            * df["exploration_score"]
        )

        # -------------------------------------------------------------
        # Greedy diversity ranking
        # -------------------------------------------------------------

        remaining = df.copy()

        selected_rows = []

        creator_counts: dict[str, int] = {}
        genre_counts: dict[str, int] = {}

        for _ in range(
            min(k, len(remaining))
        ):

            if not selected_rows:
                remaining = remaining.copy()

                remaining["selection_score"] = (
                    remaining["base_feed_score"]
                )

            else:
                remaining = remaining.copy()

                remaining["creator_penalty"] = (
                    remaining["creator_id"]
                    .astype(str)
                    .map(
                        lambda creator: 0.10
                        * creator_counts.get(
                            creator,
                            0,
                        )
                    )
                )

                remaining["genre_penalty"] = (
                    remaining["genre"]
                    .astype(str)
                    .map(
                        lambda genre: 0.05
                        * genre_counts.get(
                            genre,
                            0,
                        )
                    )
                )

                remaining["selection_score"] = (
                    remaining["base_feed_score"]
                    - remaining["creator_penalty"]
                    - remaining["genre_penalty"]
                )

            best_idx = remaining[
                "selection_score"
            ].idxmax()

            selected = remaining.loc[
                best_idx
            ].copy()

            selected_rows.append(
                selected
            )

            creator = str(
                selected["creator_id"]
            )

            genre = str(
                selected["genre"]
            )

            creator_counts[creator] = (
                creator_counts.get(
                    creator,
                    0,
                )
                + 1
            )

            genre_counts[genre] = (
                genre_counts.get(
                    genre,
                    0,
                )
                + 1
            )

            remaining = remaining.drop(
                index=best_idx
            )

            if remaining.empty:
                break

        result = pd.DataFrame(
            selected_rows
        ).reset_index(drop=True)

        result["feed_rank"] = (
            np.arange(len(result))
            + 1
        )

        return result

    # =================================================================
    # Explanations
    # =================================================================

    def _generate_explanation(
        self,
        row: pd.Series,
    ) -> str:
        """
        Generate a human-readable explanation from actual recommendation
        features.

        No invented user preference is used.
        """

        reasons: list[str] = []

        # -------------------------------------------------------------
        # User-genre affinity
        # -------------------------------------------------------------

        genre_rate = float(
            row.get(
                "user_genre_prior_smoothed_engagement_rate",
                0,
            )
        )

        if genre_rate >= 0.50:
            reasons.append(
                f"strong history with {row['genre']} content"
            )
        elif genre_rate >= 0.40:
            reasons.append(
                f"good historical response to {row['genre']} content"
            )

        # -------------------------------------------------------------
        # Freshness
        # -------------------------------------------------------------

        freshness = float(
            row.get(
                "freshness",
                0,
            )
        )

        if freshness >= 0.70:
            reasons.append(
                "recent content"
            )
        elif freshness >= 0.40:
            reasons.append(
                "relatively fresh content"
            )

        # -------------------------------------------------------------
        # Creator performance
        # -------------------------------------------------------------

        creator_rate = float(
            row.get(
                "creator_prior_smoothed_engagement_rate",
                0,
            )
        )

        if creator_rate >= 0.40:
            reasons.append(
                "creator has strong historical engagement"
            )

        # -------------------------------------------------------------
        # Content performance
        # -------------------------------------------------------------

        content_rate = float(
            row.get(
                "content_prior_smoothed_engagement_rate",
                0,
            )
        )

        if content_rate >= 0.40:
            reasons.append(
                "content has positive historical engagement"
            )

        # -------------------------------------------------------------
        # Content-based similarity
        # -------------------------------------------------------------

        similarity = float(
            row.get(
                "similarity_score",
                0,
            )
        )

        if similarity >= 0.30:
            reasons.append(
                "matches patterns in previously interacted content"
            )

        if not reasons:
            reasons.append(
                "ranked highly by the engagement model"
            )

        return " • ".join(reasons[:3])

    # =================================================================
    # Public recommendation method
    # =================================================================

    def recommendation_details(
        self,
        user_id: str,
        k: int = 10,
        progress_callback: ProgressCallback = None,
    ) -> RecommendationResult:
        """
        Generate recommendations and return detailed ranking data.

        This is the main method the Streamlit dashboard should call.
        """

        stages: list[str] = []

        # -------------------------------------------------------------
        # Stage 1
        # -------------------------------------------------------------

        user = self._get_user(user_id)

        self._progress(
            progress_callback,
            "User history loaded",
            stages,
        )

        # -------------------------------------------------------------
        # Stage 2
        # -------------------------------------------------------------

        historical_count = len(
            self.historical_interactions[
                self.historical_interactions[
                    "user_id"
                ].astype(str)
                == str(user_id)
            ]
        )

        # -------------------------------------------------------------
        # Stage 3
        # -------------------------------------------------------------

        candidates = (
            self._generate_content_candidates(
                user_id=user_id,
                candidate_pool_size=max(
                    self.candidate_pool_size,
                    k * 20,
                ),
            )
        )

        self._progress(
            progress_callback,
            (
                "Candidate pool generated "
                f"({len(candidates)} candidates)"
            ),
            stages,
        )

        # -------------------------------------------------------------
        # Stage 4
        # -------------------------------------------------------------

        seen = self.seen_content.get(
            user_id,
            set(),
        )

        candidates = candidates[
            ~candidates["content_id"].isin(seen)
        ].copy()

        candidates = candidates.reset_index(
            drop=True
        )

        self._progress(
            progress_callback,
            (
                "Previously seen content filtered "
                f"({len(candidates)} unseen candidates)"
            ),
            stages,
        )

        if candidates.empty:
            return RecommendationResult(
                user_id=user_id,
                recommendations=[],
                details=pd.DataFrame(),
                stages=stages,
            )

        # -------------------------------------------------------------
        # Stage 5
        # -------------------------------------------------------------

        candidate_features = (
            self._build_candidate_features(
                user_id=user_id,
                candidates=candidates,
            )
        )

        self._progress(
            progress_callback,
            (
                "Point-in-time features constructed "
                f"({len(candidate_features)} rows)"
            ),
            stages,
        )

        # -------------------------------------------------------------
        # Stage 6
        # -------------------------------------------------------------

        self._progress(
            progress_callback,
            (
                "53-feature contract validated"
            ),
            stages,
        )

        # -------------------------------------------------------------
        # Stage 7
        # -------------------------------------------------------------

        scored = self._score_candidates(
            candidate_features
        )

        self._progress(
            progress_callback,
            "Random Forest scoring completed",
            stages,
        )

        # -------------------------------------------------------------
        # Stage 8
        # -------------------------------------------------------------

        final_feed = self._build_final_feed(
            scored,
            k=k,
        )

        self._progress(
            progress_callback,
            "Ranking and diversity applied",
            stages,
        )

        # -------------------------------------------------------------
        # Stage 9
        # -------------------------------------------------------------

        if final_feed.empty:
            recommendations: list[str] = []

        else:
            final_feed[
                "explanation"
            ] = final_feed.apply(
                self._generate_explanation,
                axis=1,
            )

            recommendations = (
                final_feed["content_id"]
                .astype(str)
                .tolist()
            )

        self._progress(
            progress_callback,
            (
                "Recommendations generated "
                f"({len(recommendations)} items)"
            ),
            stages,
        )

        # -------------------------------------------------------------
        # Final details
        # -------------------------------------------------------------

        if not final_feed.empty:
            display_columns = [
                "feed_rank",
                "content_id",
                "creator_id",
                "genre",
                "content_type",
                "duration",
                "similarity_score",
                "engagement_score",
                "freshness",
                "base_feed_score",
                "explanation",
            ]

            display_columns = [
                column
                for column in display_columns
                if column in final_feed.columns
            ]

            details = final_feed[
                display_columns
            ].copy()

        else:
            details = pd.DataFrame()

        return RecommendationResult(
            user_id=str(user["user_id"]),
            recommendations=recommendations,
            details=details,
            stages=stages,
        )

    # =================================================================
    # Convenience method
    # =================================================================

    def recommend(
        self,
        user_id: str,
        k: int = 10,
        progress_callback: ProgressCallback = None,
    ) -> list[str]:
        """
        Simple interface returning only content IDs.
        """

        result = self.recommendation_details(
            user_id=user_id,
            k=k,
            progress_callback=progress_callback,
        )

        return result.recommendations

    # =================================================================
    # Diagnostics
    # =================================================================

    def user_history_summary(
        self,
        user_id: str,
    ) -> dict:
        """
        Return useful user-history diagnostics for the dashboard.
        """

        user = self._get_user(user_id)

        stats = self.user_stats.loc[
            user_id
        ] if user_id in self.user_stats.index else None

        if stats is None:
            return {
                "user_id": user_id,
                "history_interactions": 0,
                "unique_content": 0,
                "unique_creators": 0,
                "engagement_rate": 0.0,
                "ctr": 0.0,
                "avg_watch_time": 0.0,
                "avg_completion": 0.0,
                "is_cold_start": True,
            }

        return {
            "user_id": user_id,
            "history_interactions": int(
                stats[
                    "user_prior_interactions"
                ]
            ),
            "unique_content": int(
                stats[
                    "user_prior_unique_content"
                ]
            ),
            "unique_creators": int(
                stats[
                    "user_prior_unique_creators"
                ]
            ),
            "engagement_rate": float(
                stats[
                    "user_prior_engagement_rate"
                ]
            ),
            "ctr": float(
                stats[
                    "user_prior_ctr"
                ]
            ),
            "avg_watch_time": float(
                stats[
                    "user_prior_avg_watch_time"
                ]
            ),
            "avg_completion": float(
                stats[
                    "user_prior_avg_completion"
                ]
            ),
            "is_cold_start": False,
        }

    def model_info(self) -> dict:
        """
        Return model/recommendation-engine metadata for the dashboard.
        """

        return {
            "model_type": type(
                self.model
            ).__name__,
            "feature_count": len(
                self.feature_columns
            ),
            "candidate_pool_size": (
                self.candidate_pool_size
            ),
            "serving_cutoff": (
                self.serving_cutoff
            ),
            "eligible_content": len(
                self.eligible_content
            ),
            "historical_interactions": len(
                self.historical_interactions
            ),
            "users": len(
                self.users
            ),
            "creators": len(
                self.creators
            ),
        }